todo:
        autoAssign: true
        keyword: ['FIXME','TODO','%TODO','%FIXME','@todo','@fixme','fixme:','todo:','@fixme:','@todo:']
        bodyKeyword: ['@body','BODY', '@body:', 'body:']
        blobLines: 5
        caseSensitive: false
        label: true
        reopenClosed: true
        exclude: null